dist: bionic
addon:
  apt:
    update: true
services: docker
before_install:
- sudo apt update
- pip install --user awscli
install:
- mkdir -p ~/.local/lib && mkdir -p ~/.local/bin
- git clone https://$PV_OAUTH_TOKEN@github.com/polyverse-security/pv ~/.local/lib/pv
- ln -s ~/.local/lib/pv/pv ~/.local/bin/pv
script:
- "./upvendor.sh || travis_terminate 1"
- if [ ! -z "$(git status -s)" ]; then echo "COMMIT IS DIRTY and needs to be upvendored.";
  travis_terminate 1; fi
- pv aws ecr-login
- "./build.sh    || travis_terminate 1"
- "./test.sh     || travis_terminate 1"
- "./publish.sh  || travis_terminate 1"
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: nrYoO/dW6WK7/MVerm6mjYg+kMw1URbgrAeH61vvleWnlWDNSIhughuTWoOFV/a5sltMwwkzaYyZC/sQUCJWJpcYT9g3GuTFbkRFQpm2YxYu9sPCNrvqJWMLii5T1fsZ7aDzfi1Qb644yPqJYNRn1Wh+3UMn4THD8QqkKPPSQoi0GcNMDA11CfkVjOLd74cNHmnZAW4ORreefFNWaLIpdCRf7BFVz0PZYqypLHBUq3ot2zMhBmha7wJ0yfoki74ioBMlKU3m6Fqra/ntaK3MhIHxfcUGYXnYFgTYD9Np0xrdC5jY7Vv/E47LNB5QAPUFxAG7dmH84l0yhHeluqOtR7kzTQHcfcqBLAiz7PHq2sSQKcB/KL61GQmqcQNlIrqagwVRfYn5cYHFHMRY1A398eml9MYKlHpQU5kWOcEeq4eS9ymuyl2z56W9LOVpBc1dKz1QX4m5V6BK6LXOf2Am++Ky/xsSOM+58neNn14/N5VDwCedOtkAdzlCxEq1fwHGaSY4PyBSKGvqzJWe+4kilLllx/rNTpp4Z8rNSAcSLBshHEI2WG7sun926NxsHtzfBH9tqK79MK13BfU6e5u+VUxvH7GxgFyaiKtMKoI0TqZxs3VwhDJBCrwMD3S+TIef7YHwhwmPGyIYsaXBTuZ5ibmqogqxgEKhv1apHZPziuM=
  - secure: vPRQlHvM+OmV6cyGMg5zYMt1jLFxRbLjQyK8MCALjucsdAsBhfykTV/mNcAHUFl0OL1/QkouRM4gXs3AYxaGBUnKAo8lqZ144sRUYFaYSgp7xNVVoppMPkqYKi+thOn/n1tp29T9O9aPqKs+XFCANZXAO703saqGAVrOCTXXmmJ/6GeV99/KC2PEz5S1L9AYAOo2R2Ubba5oEVWt6Nx/fiOomjZms/eI6ApDpJUXqVuStxSrK782m2OLNYN1JWkaZ+9LJA/jANWYWnAAIosAYhqXw4QlUGBDDkKQz6YV6sJDxCDnVFAEtqRji46z86FL6s+IF/YX6P8F2TCmIgi4IZZ6JtHmpqpXzhHaZZAPt4gTcSKEqtDNAtMsP90ZrIKSOMX2y1lPbnT/WuZRDFOGOcNYfsXPIPYYpCAdgcGaleBZ1SNnhpYjwgpEljQ1Nk3xuc7kTw7bfMYul5BtV6TPXDgm5J4ZCnntrgruGkFfCmWZo+/HV4XkOHL3lcYaO3E7hiYVUr9j7bqDYIf9wLVNPkw1INR7eDS2/gVCmDI7Hm6zqVUejBY/2Apx7ZGB3UZN7Ly8YZ/2eR8zzmKia3z/9jubxsdBS/EHNMnmEkVB9S9c6M1H2HjqxNabhIz+WxT33vubqS97jJ01n9cyWJhvMQNauIdKMMaYMv3Y/kjKpBY=
  - secure: v6Xx0Azt0iIC0YYROG8MwNTDvw9Q6ySCZwT11zVPPeA8nOc+L88xrH4q8wxHgJA1VMgDS0335hgeP9bOIYZmzKkVVCSnj473EmkWA0rc5MPEQDjD0XrSITFC8dYmWjhvQb0fPpxtyS1Jp7OcjZAgznzQPL9QbR2NR6RpKVzZ5Eujmqq42lhpI6mBMgvl4Fq0mOmPlHxpOrt9N9KIOSV5HxVjuk8Gey4LugE7MUD1nC3Htku8QWuFpQNcnvDIX8GfNwG1j2x18GQJPc7BK+gdmcqtaF+N73V8mxNnHue0KPhien1BJZnaXAEF/y4u7Xu2oasLCfuDf/M7khTZDqTjUz9a9OgVFbapSbMf/Lf42hjiNvKy2ATMrfLrAyTjK5zTyVSCsxr7IYCHm0KRX8y3KT9ydV6Vi1Fh2LU7y9w6QVKU5BPQWuMUTFgycvUmB3aI1Alf5BAXQni79cc8B7adXN+7Yo+cAciNJ5oqnXeSF/pbLchguho8w9vNxds9BQu/UdB1kk0T9gSZg02R3E8JLGoGbU0UjoAK01GJxom2K6koyzwPxU4KHT62gBg1w8XctHXS1YnVSYbx1UUq9MWel04NHrAe/E8KsMJQ386ceReQYWVoscLnu3syKVtD5xZfXV1Zq5tf9MvwNl/HTWVlXXA8F9tVS77DNR6afiqktEI=
notifications:
  slack:
  - secure: RHKzteeWd4kxI6VkSALWiDW7gdrvBBzEn5Z5HanNWPW2VtgLMkDA/9MwHlwkO/Tsc9AVApG02If+jEv3dVs0ES2PKMjxQ8ddKvLR3RjlZTTDe+n0zi3nrHlyUIgHGj7qLfMoaaxECZoY6uF9Rl9OTPhVlbtIAm969OgZ2lUbFVSjeWDGoybSmeErL2TxnKBVjd0T6nWq8XxUWbAbpewIbV5bxS3rKwbAGaTgRAxZ5FSOV4F78rZNAkQdZOa44U6lFpTWRXuUjNMYw2TLuzDt12OsmAtP2rG5B/VaK7cQs7Q5yifMplc1AVnfymNuFKnwv/2+5T6ynadkOE8n29O7ZG45Cg0L3AhmP31R9RaZJ738tg7bC66Y6t8FyUdZXyhLcMTygtghfrF6vzAxF8dz6JUO88vW5GVNT6xl8x0Z/B7AEYQtLUa/XqaoexaZkyd718x16H9z1K4WB1qZ08ZrhwJFXA93Kmnur16PTBD/NrrDPA3RXd+GkczMVE5qPlJ9MFpGhd1JRJEMzCjBaONlRUJfZwOIGjSQbloZgyuPa72j1CBRf0SG91HGLZCiM7YZYlgK/mkrN33qJE7pcWjpzN1YY4/0b7ftXAg8IaqavqnNcKYJ9Is09MAb58CKmC8p7gMISk8XlQS8VEfJrX4Ri/Btm1Vezmod4zuWfhrYscc=
